#!/bin/bash

SERIAL_PORT=${SERIAL_PORT:-/dev/tty.usbserial-DN0511X8}

esptool.py \
    -b 921600 \
    -p ${SERIAL_PORT} \
    write_flash \
    0x00000000 .pio/build/unified/firmware.bin \
    0x00100000 .pio/build/unified/littlefs.bin
