#!/usr/bin/env python

import struct
import argparse
import re

parser = argparse.ArgumentParser()
parser.add_argument('input', help='input csv file', type=argparse.FileType('r'))
parser.add_argument('output', help='output binary file', type=argparse.FileType('w'))
args = parser.parse_args()

red_map = range(0, 256)
green_map = range(0, 256)
blue_map = range(0, 256)

line = args.input.readline()
while line:
    line = line.strip()
    if re.match(r'^\s*#', line):
        line = args.input.readline()
        continue
    values = line.split(',')
    if len(values) >= 4:
        in_val = int(values[0]) & 0xFF 
        red_map[in_val] = int(values[1]) & 0xFF
        green_map[in_val] = int(values[2]) & 0xFF
        blue_map[in_val] = int(values[3]) & 0xFF
    line = args.input.readline()

for x in red_map:
    args.output.write(struct.pack('>B', red_map[x]))
for x in green_map:
    args.output.write(struct.pack('>B', green_map[x]))
for x in blue_map:
    args.output.write(struct.pack('>B', blue_map[x]))
