#!/usr/bin/env python

import struct
import argparse
import re

parser = argparse.ArgumentParser()
parser.add_argument('input', help='input csv file', type=argparse.FileType('r'))
parser.add_argument('output', help='output binary file', type=argparse.FileType('w'))
args = parser.parse_args()

line = args.input.readline()
while line:
    line = line.strip()
    if re.match(r'^\s*#', line):
        line = args.input.readline()
        continue
    values = line.split(',')
    if len(values) >= 4:
        in_val = int(values[0]) & 0xFF 
        r_val = int(values[1]) & 0xFF
        g_val = int(values[1]) & 0xFF
        b_val = int(values[1]) & 0xFF
        args.output.write(struct.pack('>B', in_val))
        args.output.write(struct.pack('>B', r_val))
        args.output.write(struct.pack('>B', g_val))
        args.output.write(struct.pack('>B', b_val))
    line = args.input.readline()
