#!/bin/bash

set -e

faketty() {
    if [ "$(uname)" == "Darwin" ] ; then
	"$@"
    else
	script -qfc "$(printf "%q " "$@")" /dev/null
    fi
}

cd $(dirname $0)/..

for page in index upload_index progress2 ; do
    faketty inliner -m data.in/${page}.html > data/${page}.html
    gzip -n -f -9 data/${page}.html
    ( echo "const uint8_t ${page}_html_gz[] PROGMEM = {" ; xxd -i ./data/${page}.html.gz | tail -n +2 ) > src/static/${page}.html.gz.h
done

# remove included files from fs
rm ./data/progress2.html.gz
rm ./data/upload_index.html.gz
