#!/bin/bash

SRV="$1"
SOURCE="$2"

if [ -z "$SRV" ] ; then
    echo
    echo "$0: <path_to_save_output_files> [<path_to_local_source>]"
    echo
    exit 1
fi

if [ "$SRV" ] ; then SRV=$(realpath $SRV) ; fi

SRCVOLUME=""
SKIP_PULL="false"

if [ "$SOURCE" ] ; then
    SOURCE=$(realpath $SOURCE)
    SRCVOLUME="-v $SOURCE:/root/DreamcastHDMI"
    SKIP_PULL="true"
fi

docker run --rm -it -e "SKIP_PULL=$SKIP_PULL" -v $SRV:/srv/ $SRCVOLUME chriz2600/dreamcast-hdmi:latest /root/build
