#!/bin/bash

SRV="$1"
SOURCE="$2"

if [ -z "$SRV" ] ; then
    echo
    echo "$0: <path_to_save_output_files> [<path_to_local_source>]"
    echo
    exit 1
fi

SRCVOLUME=""

if [ ! -z "$SOURCE" ] ; then
    SRCVOLUME="-v $SOURCE:/root/DreamcastHDMI"
fi

docker run -it -v $SRV:/srv/ $SRCVOLUME chriz2600/dreamcast-hdmi /root/build
