#!/bin/bash

PRJ="$1"

if [ -z "$PRJ" ] ; then
    echo
    echo "$0: <.qpf>"
    echo
    exit 1
fi

docker run -it -v $(pwd):/build chriz2600/dreamcast-hdmi:latest /usr/local/bin/compile $PRJ
#quartus_sh --flow compile $project.qpf
#quartus_sh --set VERILOG_MACRO=_VGA_ DCxPlus-10CL025.qpf
#docker run -it -v $(pwd):/build chriz2600/dreamcast-hdmi:latest /bin/bash -l
