#!/bin/bash

SRV="$1"

if [ -z "$SRV" ] ; then
    echo
    echo "$0: <path_to_file_to_program>"
    echo
    echo "  environment variables:"
    echo "    JTAG_SERVER=<address of jtag server>"
    echo "    JTAG_PASSWD=<password of jtag server>"
    echo
    exit 1
fi

echo "/test/" | egrep -q '^(http|https)://' && echo "TRUE"

VOLUME=""
ARG=""

echo "$SRV" | egrep -q '^(http|https)://'

if [ $? -eq 0 ] ; then
    ARG="$SRV"
else 
    VOLUME="-v "$(dirname $SRV)":/srv/"
    ARG=$(basename $SRV)
fi

DEVICE=""
if command -v lsusb 2>&1 > /dev/null ; then
    _DEVICE=$(lsusb | grep Altera | awk '{print "/dev/bus/usb/"$2"/"$4}' | sed -e 's,:$,,g')
    DEVICE="--device=$_DEVICE:$_DEVICE"
fi

docker run --rm -it $VOLUME $DEVICE -e "JTAG_SERVER=$JTAG_SERVER" -e "JTAG_PASSWD=$JTAG_PASSWD" chriz2600/dreamcast-hdmi:latest /root/program $ARG
