#!/bin/bash

SRV="$1"

if [ -z "$SRV" ] ; then
    echo
    echo "$0: <path_to_file_to_program>"
    echo
    exit 1
fi

echo "/test/" | egrep -q '^(http|https)://' && echo "TRUE"

VOLUME=""
ARG=""

echo "$SRV" | egrep -q '^(http|https)://'

if [ $? -eq 0 ] ; then
    ARG="$SRV"
else 
    VOLUME="-v "$(dirname $SRV)":/srv/"
    ARG=$(basename $SRV)
fi

DEVICE=$(lsusb | grep Altera | awk '{print "/dev/bus/usb/"$2"/"$4}' | sed -e 's,:$,,g')

docker run -it $VOLUME --device=$DEVICE:$DEVICE chriz2600/dreamcast-hdmi:latest /root/program $ARG

