#!/bin/bash

docker run -it -v $(pwd):/build chriz2600/dreamcast-hdmi:latest /usr/local/bin/quartus "$@"

# IP=$(ifconfig en0 | grep inet | awk '$1=="inet" {print $2}')
# xhost + $IP
# socat TCP-LISTEN:6000,reuseaddr,fork UNIX-CLIENT:\"$DISPLAY\" &
# docker run -d -e DISPLAY=$IP:0 -v /tmp/.X11-unix:/tmp/.X11-unix chriz2600/dreamcast-hdmi:latest /bin/bash -l /opt/intelFPGA_lite/17.1/quartus/bin/quartus
