#!/bin/bash

cd $(dirname $0)

./compile DCxPlus && \
    ./create-jic DCxPlus-raw.cof && \
    ./pack-firmware output_files/DCxPlus.rbf output_files/DCxPlus.dc && \
    md5sum output_files/DCxPlus.dc && \
    ls -alF output_files/DCxPlus.dc && \
    cat output_files/DCxPlus.fit.rpt | grep '; Total logic elements               ;'
