#!/bin/bash

set -e

cd $(dirname $0)

variant=$1
if [ "$variant" = "" ] ; then
    echo "usage: $0 <std|hq2x>"
    exit 1
fi

echo "set_global_assignment -name VERILOG_MACRO $variant" > local.qsf
./compile DCxPlus
./create-jic DCxPlus.cof
./create-jic DCxPlus-raw.cof
mkdir -p output_files/$variant
for f in jic rbf ; do
    mv output_files/DCxPlus.${f} output_files/DCxPlus-default.${f}
done
cp output_files/DCxPlus-default.{jic,rbf} output_files/$variant
cat output_files/DCxPlus.fit.rpt | grep '; Total logic elements               ;'
