#!/bin/bash

set -e

cd $(dirname $0)

variant=$1
enableCustomMapper=$2
if [ "$variant" = "" ] ; then
    echo "usage: $0 <std|hq2x> [enableCustomMapper:true|false]"
    exit 1
fi

echo "set_global_assignment -name VERILOG_MACRO $variant" > local.qsf
if [ "$enableCustomMapper" = "true" ] ; then
    echo "set_global_assignment -name VERILOG_MACRO ENABLE_CUSTOM_MAPPER" >> local.qsf
fi
./compile DCxPlus
./create-jic DCxPlus.cof
./create-jic DCxPlus-raw.cof
mkdir -p output_files/$variant
for f in jic rbf ; do
    mv output_files/DCxPlus.${f} output_files/DCxPlus-default.${f}
done
mv output_files/DCxPlus-default.{jic,rbf} output_files/$variant
cp output_files/$variant/DCxPlus-default.jic output_files/DCxPlus-$variant.jic
cp output_files/$variant/DCxPlus-default.rbf output_files/DCxPlus-$variant.rbf
cat output_files/DCxPlus.fit.rpt | grep '; Total logic elements               ;'
