#!/bin/bash

set -e

cd $(dirname $0)

FWP=$(command -v firmware-packer || echo ../firmware-utils/firmware-packer)

test -x "$FWP" || {
    echo "building firmware-utils"
    cd ../firmware-utils
    make
    cd ../Core
}

for variant in std hq2x ; do
    ./build $variant
done

# backwards compatible packages
$FWP -v1 output_files/std/DCxPlus-default.rbf output_files/std/DCxPlus-default.dc
$FWP -v1 output_files/hq2x/DCxPlus-default.rbf output_files/hq2x/DCxPlus-default.dc

# modern package
$FWP -v2 output_files/std/DCxPlus-default.rbf output_files/hq2x/DCxPlus-default.rbf output_files/DCxPlus-v2.dc
# this is needed for older master/develog/experimental transition
cp output_files/std/DCxPlus-default.rbf output_files/DCxPlus-default.rbf

# debug
ls -alF output_files/std/DCxPlus-default.dc output_files/std/DCxPlus-v2.dc output_files/hq2x/DCxPlus-default.dc output_files/hq2x/DCxPlus-v2.dc
md5sum output_files/std/DCxPlus-default.dc output_files/std/DCxPlus-v2.dc output_files/hq2x/DCxPlus-default.dc output_files/hq2x/DCxPlus-v2.dc
