#!/bin/bash

cd $(dirname $0)

if [ -f ".environment" ] ; then
    source ".environment"
fi

docker run --rm -it \
    -e "JTAG_SERVER=$JTAG_SERVER" \
    -e "JTAG_PASSWD=$JTAG_PASSWD" \
    -v $(pwd):/build \
    chriz2600/quartus-lite:latest \
    /usr/local/bin/quartus_wrapper quartus_sh --flow compile "$@"

