#!/usr/bin/env bash

set -e

cd $(dirname $0)

# compile project
export SOURCE_DATE_EPOCH=$(git --no-pager log -1 --pretty='format:%ct' src)
echo $SOURCE_DATE_EPOCH

./local/prepare-index-html

pio run
pio run -t buildfs

cat data.in/changelog.in | tr -d '\n\t' > data/changelog
cp ../Core/output_files/DCxPlus-v2.dc data/firmware.dc

md5sum data/firmware.dc | awk '{print $1;}' | tr -d '\n' > data/etc/last_flash_md5
md5sum data/firmware.dc | awk '{print $1;}' | tr -d '\n' > data/firmware.dc.md5
md5sum data/index.html.gz | awk '{print $1;}' | tr -d '\n' > data/index.html.gz.md5
md5sum data/index.html.gz | awk '{print $1;}' | tr -d '\n' > data/esp.index.html.gz.md5

cp .pio/build/unified/firmware.bin .pio/build/
cp .pio/build/unified/spiffs.bin .pio/build/

for variant in std hq2x; do
    mkdir -p build/$variant
    mkdir -p .pio/build/$variant/

    cp .pio/build/unified/firmware.bin .pio/build/$variant/
    cp .pio/build/unified/spiffs.bin .pio/build/$variant/
done
