#!/bin/bash

set -e

AARGS=""
if [ "$1" == "-n" ] ; then
    AARGS="--no-cache"
fi

cd $(dirname $0)

echo building chriz2600/dreamcast-hdmi
docker build $AARGS -t chriz2600/dreamcast-hdmi .
echo 
echo "to add to docker hub: "
echo "docker push chriz2600/dreamcast-hdmi"
echo
