#!/bin/bash

set -e

cd $(dirname $0)

echo building chriz2600/dreamcast-hdmi
docker build -t chriz2600/dreamcast-hdmi .
echo 
echo "to add to docker hub: "
echo "docker push chriz2600/dreamcast-hdmi"
echo
