#!/bin/bash

cd $(dirname $0)/..

hostname=${ESP_HOSTNAME:-dc-firmware-manager.local}

curl -s --basic --user dchdmi:testtest \
     -o /dev/null "http://${hostname}/flash/index"

while (true) ; do
    res=$(curl -s --basic --user dchdmi:testtest "http://${hostname}/progress")
    if [ "$res" == "100" ] ; then
        echo "done."
        exit 0
    fi
    if [[ $res == ERROR* ]] ; then
        echo "$res"
        exit 1
    fi
    sleep 1
done
