#!/bin/bash

set -e

cd $(dirname $0)

IMAGE_NAME="chriz2600/dc-publish-utils"

echo "building ${IMAGE_NAME}"
docker build -t ${IMAGE_NAME}:latest .
echo 
echo "to add to docker hub: "
echo "docker push ${IMAGE_NAME}"
echo
