#!/bin/bash -l

set -e

source $(dirname $0)/build.projects

cd /root/DreamcastHDMI/
CWD=$(pwd)

if [ "$SKIP_PULL" != "true" ] ; then 
    git pull
fi

# build projects
doBuildProjects

# copy files to output folder
cd $CWD
cp Core/output_files/*.jic /srv/
cp Core/output_files/*.rbf /srv/
cp Core/output_files/*.dc /srv/
