#!/bin/bash -l

FILE="$1"
PGM=""

echo "$FILE" | egrep -q '^(http|https)://'

if [ $? -eq 0 ] ; then
    curl -s -o /srv/file-to-program.jic "$FILE"
    PGM="/srv/file-to-program.jic"
else 
    PGM="/srv/$FILE"
fi

PROGRAMMER=$(jtagconfig --enum  | head -n 1 | sed 's/1) //')

quartus_pgm -c "$PROGRAMMER" -m jtag -o "ipv;$PGM"

